import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen">
          <div className="flex h-screen">
            <div className="sm:flex-[2.5] min-w-[290px] max-w-[290px] sm:block hidden">
            <Sidebar />
            </div>
            <main className="sm:flex-[9.5] flex-1 min-w-0 overflow-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
